Repository auth0/auth0-spa-js, pull requests merged in 2019-10, with the labels that each got.

#231 Fix query parsing when using hash routing
  __tests__/index.test.ts
  src/Auth0Client.ts
Labels: small

#232 Fix safari10 initialization error
  FAQ.md
  __tests__/index.test.ts
  __tests__/utils.test.ts
  src/index.ts
  src/utils.ts
  static/index.html
Labels: small

#242 Fix IE msCrypto.subtle usage
  __tests__/utils.test.ts
  src/utils.ts
Labels: tiny

#238 Add 'lock' to prevent `getTokenSilently` to be invoked in parallel
  __mocks__/browser-tabs-lock/index.ts
  __tests__/index.test.ts
  package-lock.json
  package.json
  src/Auth0Client.ts
  static/index.html
Labels: medium

#248 Improved OIDC compliance
  __tests__/index.test.ts
  __tests__/jwt.test.ts
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/global.ts
  src/jwt.ts
Labels: medium

#252 Fix for race condition when using `sha256` on IE11
  __tests__/utils.test.ts
  src/utils.ts
  static/index.html
Labels: small

#256 Document leeway default value
  src/global.ts
Labels: review:tiny

#261 Updated types path in package.json
  package-lock.json
  package.json
Labels: review:tiny

#260 Update typescript definition for max_age param
  __tests__/index.test.ts
  __tests__/jwt.test.ts
  src/Auth0Client.ts
  src/global.ts
  src/jwt.ts
Labels: CH: Fixed, review:tiny

#264 Moved prepublish script into the prepack stage
  package.json
  scripts/prepack.js
Labels: CH: Fixed, review:tiny

#265 Release 1.4.2
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: review:tiny

#249 Add a new property 'fragment' to be appended to the authorize URL on redirect
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/global.ts
Labels: CH: Added, [Goalie] Review Required, review:small

#266 Release 1.5.0
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: review:tiny
