Repository auth0/auth0-spa-js, pull requests merged in 2020-10, with the labels that each got.

#592 [SDK-1994] GMaps breaks SPA JS on IE11
  src/index.ts
Labels: small

#585 Dependency upgrade
  package-lock.json
  package.json
Labels: dependencies, tiny

#586 Add an option to extend cookie expire day
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/constants.ts
  src/global.ts
Labels: CH: Added, medium

#603 [SDK-2042] Fallback option for transactions using cookies
  __tests__/Auth0Client.test.ts
  __tests__/cache.test.ts
  __tests__/transaction-manager.test.ts
  cypress/integration/loginWithRedirect.js
  cypress/support/commands.js
  cypress/support/utils.js
  jest.config.js
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/global.ts
  static/index.html
Labels: CH: Added

#609 Updates issue template config to fix broken link
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, tiny

#612 [SDK-2092] Do not use Web Worker for Safari < 12.1
  __tests__/Auth0Client.test.ts
  src/Auth0Client.ts
  src/token.worker.ts
  src/user-agent.ts
Labels: CH: Changed

#613 [SDK-2037] Remove cacheLocation guard from checkSession
  src/Auth0Client.ts
Labels: CH: Changed

#422 Fix leaking windows message event listener
  __tests__/utils.test.ts
  src/utils.ts
Labels: CH: Fixed, review:small

#614 Release 1.13.1
  .gitignore
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/user-agent.ts
  src/version.ts
  typedoc.js
Labels: review:small

#617 [SDK-2046] Move and refactor remaining loginWithRedirect tests
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
  __tests__/helpers.ts
  __tests__/index.test.ts
Labels: review:small

#618 [SDK-2048] Move and refactor getUser tests
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:small
