Repository auth0/auth0-spa-js, pull requests merged in 2020-01, with the labels that each got.

#303 [SDK-1178] Local Storage caching mechanism
  .vscode/launch.json
  README.md
  __tests__/cache.test.ts
  __tests__/index.test.ts
  cypress/integration/getTokenSilently.js
  cypress/integration/loginWithRedirect.js
  jest.config.js
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/cache.ts
  src/global.ts
  src/index.ts
  static/index.html
Labels: CH: Added, review:medium

#325 Included the polyfill for String.includes
  src/index.ts
Labels: CH: Fixed, review:tiny

#326 Release v1.6.1
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: review:tiny

#315 [SDK-1179] Support for rotating refresh tokens
  __tests__/index.test.ts
  __tests__/utils.test.ts
  cypress/integration/getTokenSilently.js
  cypress/support/commands.js
  src/Auth0Client.ts
  src/cache.ts
  src/errors.ts
  src/global.ts
  src/index.ts
  src/utils.ts
  static/index.html
Labels: CH: Added, review:medium

#329 [SDK-1258] Remove future iat check
  __tests__/jwt.test.ts
  src/jwt.ts
Labels: CH: Changed, review:tiny

#331 Release 1.6.2
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: review:tiny

#332 Enchancements to the build process - changelog generation
  .gitignore
  package.json
  scripts/changelog.js
  scripts/cleanup.js
  scripts/release.js
Labels: review:small

#333 Fixed issue with cache not retaining refresh token
  __tests__/cache.test.ts
  __tests__/index.test.ts
  cypress/integration/getTokenSilently.js
  src/Auth0Client.ts
  src/cache.ts
  static/index.html
Labels: CH: Changed, review:small

#334 Prepare 1.7.0-beta.2
  CHANGELOG.md
  README.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  docs/interfaces/tokenendpointoptions.html
  package.json
  src/version.ts
Labels: review:tiny

#339 No longer acquires a browser lock if there was a hit on the cache
  __tests__/index.test.ts
  src/Auth0Client.ts
Labels: CH: Fixed, review:tiny

#318 Use user provided params on silent login
  __tests__/index.test.ts
  src/Auth0Client.ts
Labels: CH: Fixed, review:tiny

#341 Send same redirect_uri as /authorize to /token
  __tests__/index.test.ts
  __tests__/transaction-manager.test.ts
  src/Auth0Client.ts
  src/global.ts
  src/transaction-manager.ts
Labels: CH: Fixed, review:tiny

#342 Release 1.6.3
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: review:tiny
