Repository auth0/auth0-spa-js, pull requests merged in 2020-12, with the labels that each got.

#659 [SDK-2172] Add SDK metrics to all API calls
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/Auth0Client/helpers.ts
  __tests__/Auth0Client/loginWithPopup.test.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  __tests__/utils.test.ts
  src/Auth0Client.ts
  src/constants.ts
  src/global.ts
  src/utils.ts
Labels: review:small

#661 [SDK-2025] Internal module refactor
  .vscode/settings.json
  __tests__/Auth0Client/buildLogoutUrl.test.ts
  __tests__/Auth0Client/checkSession.test.ts
  __tests__/Auth0Client/constructor.test.ts
  __tests__/Auth0Client/getIdTokenClaims.test.ts
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/Auth0Client/getTokenWithPopup.test.ts
  __tests__/Auth0Client/getUser.test.ts
  __tests__/Auth0Client/handleRedirectCallback.test.ts
  __tests__/Auth0Client/isAuthenticated.test.ts
  __tests__/Auth0Client/loginWithPopup.test.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  __tests__/Auth0Client/logout.test.ts
  __tests__/api.test.ts
  __tests__/http.test.ts
  __tests__/index.test.ts
  __tests__/token.worker.test.ts
  __tests__/utils.test.ts
  jest.config.js
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/api.ts
  src/cache.ts
  src/global.ts
  src/http.ts
  src/jwt.ts
  src/utils.ts
  src/worker/__mocks__/token.worker.ts
  src/worker/token.worker.ts
  src/worker/worker.types.ts
  src/worker/worker.utils.ts
  tsconfig.json
  tsconfig.test.json
  typedoc.js
Labels: enhancement, review:large

#664 Avoid the possibility to do simultaneous calls to the token endpoint
  __mocks__/browser-tabs-lock/index.ts
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/promise-utils.test.ts
  src/Auth0Client.ts
  src/promise-utils.ts
Labels: review:large

#665 [SDK-2183] Add warning when requested scopes differ from retrieved scopes
  __tests__/scope.test.ts
  package.json
  src/api.ts
  src/scope.ts
Labels: review:small

#666 [SDK-2173] Expand on behaviour of checkSession in docs
  README.md
  src/Auth0Client.ts
Labels: documentation, review:tiny

#652 [SDK-2039] Change cache lookup mechanism
  __tests__/cache.test.ts
  __tests__/constants.ts
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/cache.ts
Labels: CH: Changed, review:small

#668 [SDK-1739] Recover and logout when throwing invalid_grant on Refresh Token
  __tests__/Auth0Client/getTokenSilently.test.ts
  src/Auth0Client.ts
  src/constants.ts
  static/index.html
Labels: review:medium

#670 Release 1.13.5
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/classes/user.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/constants.ts
  src/version.ts
  typedoc.js
Labels: review:small

#673 Do not send useCookiesForTransactions to authorize request
  src/Auth0Client.ts
Labels: review:tiny

#674 Update 1.13.5 changelog to include getUser types
  CHANGELOG.md
Labels: review:tiny

#678 Remove the nonce check in handleRedirectCallback
  src/Auth0Client.ts
Labels: CH: Fixed, review:tiny

#677 Enable use of a different port for the playground
  DEVELOPMENT.md
  cypress/integration/loginWithRedirect.js
  rollup.config.js
  static/index.html
Labels: enhancement, review:small
