Repository auth0/auth0-spa-js, pull requests merged in 2020-06, with the labels that each got.

#490 [SDK-1695] Add `auth0Client` option so wrapper libraries can send their own client info
  __tests__/Auth0Client.test.ts
  __tests__/helpers.ts
  __tests__/index.test.ts
  jest.config.js
  src/Auth0Client.ts
  src/global.ts
  typedoc.js
Labels: CH: Added, small

#484 Update docs for returnTo and client_id params on logout
  src/global.ts
Labels: CH: Fixed, documentation, tiny

#482 Add `checkSession` and ignore recoverable errors
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/constants.ts
  src/index.ts
Labels: CH: Added, medium

#492 Release 1.9.0
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/version.ts
Labels: tiny

#493 Update cdn url to reflect new minor
  README.md
Labels: tiny

#491 [SDK-1696] Allow caller of cache.get to specify an expiry time adjustment
  __tests__/Auth0Client.test.ts
  __tests__/cache.test.ts
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/cache.ts
  static/index.html
Labels: CH: Changed, small

#497 [SDK-1699] Fix ID token validation for auth_time
  __tests__/jwt.test.ts
  src/jwt.ts
Labels: CH: Fixed, small

#503 Don't include mocks in build
  tsconfig.json
Labels: CH: Fixed, tiny

#472 Add secure attribute to cookies if served over HTTPS
  __tests__/storage.test.ts
  src/storage.ts
Labels: CH: Fixed, tiny

#509 Release v1.10.0
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release, tiny
