Repository auth0/auth0-spa-js, pull requests merged in 2020-02, with the labels that each got.

#348 [SDK-1308] Return appState value on error from handleRedirectCallback
  __tests__/index.test.ts
  cypress/integration/getTokenSilently.js
  cypress/integration/loginWithRedirect.js
  src/Auth0Client.ts
  src/errors.ts
  static/index.html
Labels: CH: Changed, enhancement, small

#349 Configure CI build to store screenshots from integration tests
  .circleci/config.yml
Labels: enhancement, tiny

#353 Release v1.6.4
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release, small

#355 Fixed CDN version in readme.md
  README.md
Labels: tiny

#354 [SDK-1352] Removed setTimeout cache removal in favour of removal-on-read
  __tests__/cache.test.ts
  src/cache.ts
Labels: CH: Changed, beta, small

#336 [SDK-1279] getTokenSilently retry logic
  __tests__/index.test.ts
  __tests__/utils.test.ts
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/constants.ts
  src/global.ts
  src/index.ts
  src/utils.ts
Labels: CH: Changed, beta, tiny

#352 [SDK-1352] Stop checking `isAuthenticated` cookie on initialization when using local storage
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/constants.ts
  src/global.ts
  src/index.ts
Labels: CH: Changed, beta, small

#358 Release 1.7.0-beta.3
  CHANGELOG.md
  README.md
  docs/assets/js/search.js
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: beta, tiny

#356 center popup over owner window
  __tests__/utils.test.ts
  package-lock.json
  src/utils.ts
Labels: CH: Changed, enhancement, feature request, size: small
