Repository auth0/auth0-spa-js, pull requests merged in 2020-11, with the labels that each got.

#620 Update Readme.md
  README.md
Labels: tiny

#628 Add command to easily show coverage report
  DEVELOPMENT.md
  package.json
Labels: documentation, enhancement, review:tiny

#622 [SDK-2049] Move and refactor getIdTokenClaims tests
  .DS_Store
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:small

#624 [SDK-2050] Move and refactor isAuthenticated tests
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:small

#630 [SDK-2036] Performance and bundle size tooling
  .circleci/config.yml
  .gitignore
  DEVELOPMENT.md
  package-lock.json
  package.json
  rollup.config.js
  static/perf.html
Labels: enhancement, review:small

#631 [SDK-2121] Add support for token validation for Organizations
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  __tests__/jwt.test.ts
  src/Auth0Client.ts
  src/global.ts
  src/jwt.ts
  src/transaction-manager.ts
Labels: CH: Added, enhancement, review:small

#632 Release 1.13.2
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release, review:small

#629 Rework helper functions for Auth0Client
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
Labels: review:small

#626 [SDK-2029] Run framework integration automatically
  .circleci/config.yml
Labels: review:medium

#633 [SDK-2069] Update Jest to latest
  .circleci/config.yml
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  package-lock.json
  package.json
Labels: dependencies, enhancement, review:tiny

#635 Update circle config to avoid duplicate image name
  .circleci/config.yml
Labels: review:tiny

#637 [SDK-2053] Refactor and move logout tests
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
  __tests__/constants.ts
  __tests__/index.test.ts
Labels: enhancement, review:medium

#639 [SDK-2156] Heed timeoutInSeconds when calling getTokenSilently with refresh tokens
  __tests__/index.test.ts
  src/Auth0Client.ts
Labels: CH: Fixed, review:small

#640 [SDK-2047] Move and refactor handleRedirectCallback tests
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:medium

#642 Release 1.13.3
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release, review:small

#643 Add codecov support and modify build
  .circleci/config.yml
  codecov.yml
  package-lock.json
  package.json
Labels: review:tiny

#645 [SDK-2052] Refactor getTokenWithPopup tests
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  jest.config.js
  src/Auth0Client.ts
Labels: review:small

#641 [SDK-2045] Move and refactor buildAuthorizeUrl tests
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:medium

#648 [SDK-2154] Update e2e tests
  cypress/integration/getTokenSilently.js
  cypress/integration/handleRedirectCallback.js
  cypress/integration/initialisation.js
  cypress/integration/loginWithRedirect.js
  cypress/integration/logout.js
  cypress/support/commands.js
  cypress/support/utils.js
  package.json
  static/index.html
Labels: review:small

#644 [SDK-2051] Move and refactor getTokenSilently tests
  __tests__/Auth0Client.helpers.ts
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:medium

#649 [SDK-2162] Move and refactor buildLogoutUrl tests
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
Labels: review:tiny

#651 [SDK-1159] Use generics for getUser
  src/Auth0Client.ts
  src/cache.ts
  src/global.ts
Labels: review:tiny

#653 [SDK-2157] Move tests to different files
  __tests__/Auth0Client.test.ts
  __tests__/Auth0Client/buildLogoutUrl.test.ts
  __tests__/Auth0Client/checkSession.test.ts
  __tests__/Auth0Client/constructor.test.ts
  __tests__/Auth0Client/getIdTokenClaims.test.ts
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/Auth0Client/getTokenWithPopup.test.ts
  __tests__/Auth0Client/getUser.test.ts
  __tests__/Auth0Client/handleRedirectCallback.test.ts
  __tests__/Auth0Client/helpers.ts
  __tests__/Auth0Client/isAuthenticated.test.ts
  __tests__/Auth0Client/loginWithPopup.test.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  __tests__/Auth0Client/logout.test.ts
  jest.config.js
  package.json
Labels: review:medium
