Repository auth0/auth0-spa-js, pull requests merged in 2020-05, with the labels that each got.

#451 Fix issue with create-react-app webpack build
  package-lock.json
  package.json
  rollup.config.js
Labels: CH: Fixed, tiny

#453 Release 1.8.1
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/version.ts
Labels: tiny

#460 Update SDK version in the readme
  README.md
Labels: tiny

#461 [SDK-1649] Fix issue where cache was missed when scope parameter was provided
  __tests__/Auth0Client.test.ts
  src/Auth0Client.ts
Labels: CH: Fixed, tiny

#466 Playground: concatenated ID and Access Token readout for readability
  static/index.html
Labels: tiny

#465 [SDK-1634] Pass custom options to the token endpoint
  __tests__/Auth0Client.test.ts
  src/Auth0Client.ts
  src/global.ts
  static/index.html
Labels: CH: Fixed, small

#471 [SDK-1640] Allow the client to be constructed in a Node SSR environment
  __tests__/ssr.test.ts
  src/Auth0Client.ts
  src/transaction-manager.ts
Labels: CH: Changed, small

#475 Add a basic DEVELOPMENT file to explain common scenarios
  DEVELOPMENT.md
Labels: documentation, tiny

#481 Release 1.8.2
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/version.ts
Labels: tiny
