Repository auth0/auth0-spa-js, pull requests merged in 2020-03, with the labels that each got.

#367 Fix error in library type definitions
  src/index.ts
Labels: CH: Fixed, beta, bug, size: tiny

#364 [SDK-1386] Fall back to iframe method if no refresh token is available
  __tests__/index.test.ts
  cypress/integration/getTokenSilently.js
  src/Auth0Client.ts
Labels: CH: Changed, beta, size: small

#369 [SDK-1125] createAuth0Client now throws errors that are not login_required
  __tests__/index.test.ts
  src/index.ts
Labels: CH: Fixed, size: small

#370 [SDK-1386] Release 1.7.0-beta.4
  CHANGELOG.md
  README.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release, size: tiny

#363 Updated stalebot configuration
  .github/stale.yml
Labels: size: tiny

#362 [SDK-1099] Add `localOnly` logout option
  __tests__/index.test.ts
  src/Auth0Client.ts
  src/global.ts
Labels: CH: Changed, enhancement, size: small

#371 Update dependencies within semver ranges
  package-lock.json
  package.json
Labels: CH: Changed, dependencies, size: tiny

#368 [SDK-1395] Refactor loginWithPopup to optionally accept an existing popup window
  __tests__/index.test.ts
  __tests__/utils.test.ts
  src/Auth0Client.ts
  src/global.ts
  src/utils.ts
  static/index.html
Labels: CH: Added, bug, size: small

#377 [SDK-1379] Export constructor
  README.md
  __tests__/index.test.ts
  cypress/integration/initialisation.js
  package.json
  rollup.config.js
  src/Auth0Client.ts
  src/index.cjs.ts
  src/index.ts
Labels: CH: Added

#374 handleRedirectCallback wont pass redirect_uri undefined if not set in transaction
  __tests__/index.test.ts
  src/Auth0Client.ts
Labels: CH: Changed, small

#378 Changed support + feedback wording.
  README.md
Labels: tiny

#379 Release 1.7.0
  CHANGELOG.md
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/fakelock.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release

#386 Fix typings to allow custom claims in ID token
  src/global.ts
Labels: CH: Fixed, tiny

#385 [SDK-1379] Export constructor
  README.md
  __tests__/index.test.ts
  cypress/integration/initialisation.js
  package.json
  rollup.config.js
  src/Auth0Client.ts
  src/index.cjs.ts
  src/index.ts
Labels: CH: Changed, beta

#395 Clean up temp files after running release process
  scripts/release.js
Labels: enhancement, tiny
