Repository auth0/auth0-spa-js, pull requests merged in 2020-04, with the labels that each got.

#405 [SDK-1507] Dependency upgrade
  .circleci/config.yml
  __tests__/index.test.ts
  __tests__/jwt.test.ts
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
Labels: CH: Security, beta, dependencies

#409 [SDK-1516] Web Workers
  .gitignore
  .vscode/launch.json
  Jenkinsfile
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  __tests__/token.worker.test.ts
  package-lock.json
  package.json
  rollup.config.js
  scripts/prepack.js
  src/Auth0Client.ts
  src/__mocks__/token.worker.ts
  src/constants.ts
  src/index.cjs.ts
  src/index.ts
  src/token.worker.ts
  src/utils.ts
  static/index.html
Labels: CH: Changed, beta, medium

#415 [SDK-1507] Updated readme with info on refresh tokens
  README.md
Labels: tiny

#414 Fallback to iframe method when getTokenSilently is given a specific audience
  __tests__/index.test.ts
  src/Auth0Client.ts
  static/index.html
Labels: small

#399 Check if iframe is still in body before removing
  __tests__/utils.test.ts
  src/utils.ts
Labels: CH: Fixed, tiny

#410 Check if source of event exists before closing it
  src/utils.ts
Labels: tiny

#421 Release 1.7.0
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/Auth0Client.ts
  src/index.cjs.ts
  src/token.worker.ts
  src/version.ts
Labels: release

#423 Updated readme to include information about the RT fallback
  README.md
Labels: documentation, tiny

#431 Reset prettier config to pre-2.0 defaults, reformatted some files
  .prettierrc
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  __tests__/jwt.test.ts
  scripts/changelog.js
  src/Auth0Client.ts
  src/cache.ts
  src/token.worker.ts
  src/utils.ts
Labels: small

#426 include polyfill for Set
  src/index.ts
Labels: CH: Added, tiny

#441 Updated `login_hint` js docs to clarify usage with Lock
  src/global.ts
Labels: CH: Fixed, documentation

#442 Moved es-check to build script
  package.json
Labels: tiny

#443 Update rollup-plugin-web-worker-loader to 1.1.1
  package-lock.json
  package.json
  rollup.config.js
  static/index.html
Labels: CH: Fixed, dependencies, tiny

#435 [SDK-1417] Customizable default scopes
  README.md
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  __tests__/scope.test.ts
  __tests__/utils.test.ts
  src/Auth0Client.ts
  src/constants.ts
  src/global.ts
  src/scope.ts
  src/utils.ts
Labels: CH: Added, feature request, medium
