Repository auth0/auth0-spa-js, pull requests merged in 2020-09, with the labels that each got.

#564 [SDK-1837] Session storage support for transactions
  __tests__/index.test.ts
  __tests__/storage.test.ts
  __tests__/transaction-manager.test.ts
  cypress/integration/getTokenSilently.js
  cypress/support/commands.js
  cypress/support/utils.js
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/storage.ts
  src/transaction-manager.ts
  static/index.html
Labels: CH: Fixed, large

#547 fix: add missing types to utils.ts and errors.ts
  src/errors.ts
  src/utils.ts
  yarn.lock
Labels: small

#568 [SDK-1858] Create legacy samsite cookie by default
  __tests__/Auth0Client.test.ts
  __tests__/index.test.ts
  __tests__/storage.test.ts
  src/Auth0Client.ts
  src/global.ts
  src/storage.ts
Labels: CH: Added, small

#569 Dependency updates
  .gitignore
  docs/assets/js/main.js
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  yarn.lock
Labels: CH: Changed, dependencies, small

#571 Release 1.12.0
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/version.ts
Labels: tiny

#578 Fix SSR
  __tests__/cache.test.ts
  __tests__/transaction-manager.test.ts
  jest.config.js
  src/storage.ts
Labels: CH: Fixed, small

#579 Release 1.12.1
  CHANGELOG.md
  README.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/version.ts
Labels: release, small

#588 Node v to active LTS tests require worker_threads
  DEVELOPMENT.md
Labels: CH: Changed, tiny
