Repository auth0/auth0-spa-js, pull requests merged in 2020-07, with the labels that each got.

#520 [SDK-1650] Add `message` to errors that don't have one
  __tests__/utils.test.ts
  src/errors.ts
  src/utils.ts
Labels: CH: Added, small

#521 [SDK-1790] use refresh_tokens with multiple audiences
  __tests__/index.test.ts
  __tests__/utils.test.ts
  cypress/integration/getTokenSilently.js
  cypress/support/commands.js
  cypress/support/utils.js
  src/Auth0Client.ts
  src/global.ts
  src/token.worker.ts
  src/utils.ts
  static/index.html
Labels: CH: Added, medium

#525 [SDK-1798] prevent unnecessary token requests
  __tests__/Auth0Client.test.ts
  src/Auth0Client.ts
Labels: CH: Fixed, small

#524 [SDK-1789] Add custom initial options to the 2 getToken methods
  __tests__/Auth0Client.test.ts
  src/Auth0Client.ts
Labels: CH: Fixed, small

#523 [SDK-1560] Allow issuer as url
  __tests__/Auth0Client.test.ts
  src/Auth0Client.ts
Labels: CH: Added, small

#530 audit lodash
  package-lock.json
  package.json
Labels: tiny

#532 Store test results, configure Cypress artefact paths
  .circleci/config.yml
  .gitignore
  jest.config.js
  package-lock.json
  package.json
Labels: tiny

#534 Exclude windows absolute paths as well as posix
  rollup.config.js
Labels: CH: Fixed, tiny
