Repository auth0/auth0-spa-js, pull requests merged in 2021-09, with the labels that each got.

#778 Automatically publish package to NPM on version change
  .circleci/config.yml
  package.json
Labels: review:small

#786 Prepare for release script
  .shiprc
  README.md
Labels: review:small

#792 Remove old release script
  package.json
  scripts/cleanup.js
  scripts/release.js
Labels: review:tiny

#790 [SDK-2320] Throw login_required error in SPA SDK if running in a cross-origin is…
  __tests__/Auth0Client/getTokenSilently.test.ts
  src/Auth0Client.ts
Labels: CH: Changed, review:small

#789 [SDK-2750] Expose mfa_token from the mfa_required error when getting new tokens
  __tests__/http.test.ts
  src/errors.ts
  src/http.ts
  src/index.cjs.ts
  src/index.ts
Labels: CH: Added, review:small

#788 [SDK-2692] Remember organization ID for silent authentication
  __tests__/Auth0Client/checkSession.test.ts
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/Auth0Client/helpers.ts
  __tests__/Auth0Client/loginWithPopup.test.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  __tests__/Auth0Client/logout.test.ts
  __tests__/storage.test.ts
  cypress/integration/getTokenSilently.js
  cypress/integration/loginWithRedirect.js
  cypress/support/commands.js
  scripts/oidc-provider.js
  src/Auth0Client.ts
  src/storage.ts
  static/index.html
Labels: CH: Fixed, review:medium

#796 [SDK-2759] Re-scoping cookies and transactions to client ID
  .vscode/launch.json
  __tests__/Auth0Client/checkSession.test.ts
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/Auth0Client/loginWithPopup.test.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  __tests__/Auth0Client/logout.test.ts
  __tests__/cache/cache-manager.test.ts
  __tests__/index.test.ts
  __tests__/transaction-manager.test.ts
  cypress/integration/loginWithRedirect.js
  cypress/integration/multiple_clients.js
  cypress/support/utils.js
  scripts/oidc-provider.js
  src/Auth0Client.ts
  src/cache/cache-manager.ts
  src/cache/key-manifest.ts
  src/transaction-manager.ts
  static/index.html
  static/multiple_clients.html
Labels: CH: Changed, review:medium

#801 [SDK-2795] Ensure getTokenWithPopup uses the cache
  __tests__/Auth0Client/getTokenWithPopup.test.ts
  __tests__/Auth0Client/helpers.ts
  src/Auth0Client.ts
  src/global.ts
Labels: CH: Changed, review:medium

#802 [SDK-2793] Ability to define a custom now provider
  __tests__/cache/cache-manager.test.ts
  __tests__/jwt.test.ts
  src/Auth0Client.ts
  src/cache/cache-manager.ts
  src/constants.ts
  src/global.ts
  src/jwt.ts
Labels: review:medium
