Repository auth0/auth0-spa-js, pull requests merged in 2021-11, with the labels that each got.

#832 Add documentation for checkSession usage in private tabs
  package-lock.json
  src/Auth0Client.ts
  src/index.ts
Labels: documentation, review:tiny

#835 Add docs to clarity on silent auth + MFA usage
  FAQ.md
Labels: documentation, review:tiny

#840 Prevent nowProvider from being passed to authorize endpoint
  __tests__/Auth0Client/constructor.test.ts
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/Auth0Client/helpers.ts
  __tests__/Auth0Client/loginWithPopup.test.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  src/Auth0Client.ts
  tsconfig.test.json
Labels: CH: Fixed, review:small

#841 [SDK-2943] Add check for state in handleRedirectCallback
  __tests__/Auth0Client/handleRedirectCallback.test.ts
  __tests__/transaction-manager.test.ts
  package-lock.json
  package.json
  src/Auth0Client.ts
  src/storage.ts
  src/transaction-manager.ts
Labels: CH: Fixed, review:small

#846 Make RedirectLoginOptions and RedirectLoginResult accept generic AppState
  src/Auth0Client.ts
  src/global.ts
Labels: CH: Changed, review:medium
