Repository auth0/auth0-spa-js, pull requests merged in 2021-03, with the labels that each got.

#712 Revert [SDK-2183] Add warning when requested scopes differ from retrieved scopes
  __tests__/scope.test.ts
  src/api.ts
  src/scope.ts
Labels: CH: Fixed, review:small

#714 Updated minor syntax, to allow for TypeScript compiler to be happier
  src/Auth0Client.ts
Labels: CH: Fixed, review:small

#716 Export errors for type checking
  src/errors.ts
  src/index.cjs.ts
  src/index.ts
  static/index.html
Labels: CH: Added, review:small

#720 [SDK-2290] Add support for Organizations
  .circleci/config.yml
  README.md
  src/global.ts
  static/index.html
Labels: CH: Added, review:small

#721 Add screen_hint parameter to BaseLoginOptions
  src/global.ts
Labels: CH: Changed, enhancement, review:tiny

#722 Fix invitations usage example in readme
  README.md
Labels: documentation, review:tiny

#717 feat(loginWithRedirect): add redirectMethod option
  .circleci/config.yml
  __tests__/Auth0Client/helpers.ts
  __tests__/Auth0Client/loginWithRedirect.test.ts
  src/Auth0Client.ts
  src/global.ts
Labels: enhancement, review:small

#723 Release v1.14.0
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/classes/user.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package-lock.json
  package.json
  src/version.ts
Labels: release, review:tiny
