Repository auth0/auth0-spa-js, pull requests merged in 2021-01, with the labels that each got.

#679 Do not use AbortController in the worker if not available
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/api.test.ts
  __tests__/token.worker.test.ts
  src/Auth0Client.ts
  src/user-agent.ts
  src/worker/token.worker.ts
Labels: CH: Changed, review:small

#687 Update wait-on to solve security vulnerability
  package-lock.json
  package.json
Labels: CH: Security, review:tiny

#688 Only use jest maxWorkers on CI
  .circleci/config.yml
  package.json
Labels: review:tiny

#689 [SDK-2238] Only use timeout promise when using fetchWithTimeout without a worker
  __tests__/Auth0Client/getTokenSilently.test.ts
  __tests__/http.test.ts
  src/http.ts
  src/worker/token.worker.ts
Labels: CH: Changed, review:small

#690 Update docs for getIdTokenClaims and getUser
  src/Auth0Client.ts
Labels: CH: Changed, documentation, review:tiny

#691 Release 1.13.6
  CHANGELOG.md
  docs/classes/auth0client.html
  docs/classes/authenticationerror.html
  docs/classes/genericerror.html
  docs/classes/popuptimeouterror.html
  docs/classes/timeouterror.html
  docs/classes/user.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  package.json
  src/version.ts
Labels: release, review:tiny

#692 Add link to info about storage options on cacheLocation
  src/global.ts
Labels: documentation, review:tiny
